Firebase function example
talentlessguy/tinyhttp pull request #171
Opened 2020-10-22 18:08 UTC by iketiunn

Just using this awesome lib with firebase function, so I made a example for it :)

ref: https://github.com/talentlessguy/tinyhttp/issues/21

2020-10-22 19:40 UTC, talentlessguy requested changes

2020-10-22 19:40 UTC, talentlessguy commented on examples/firebase-functions/README.md
> +#### Install dependencies / Setup
Readme must be the same style as any other example in the project

and instructions must use `pnpm` instead of `npm`

2020-10-22 19:40 UTC, talentlessguy commented on examples/firebase-functions/functions/index.js
> +const functions = require('firebase-functions')
all examples must use ESM, unless there is no other way than using CommonJS

2020-10-22 19:42 UTC, talentlessguy commented
@iketiunn wow, thanks for submitting this example

and special thanks for kind words :heart: 

i just submitted some changes to do, pls check each one and fix the issues so I can merge it :3

2020-10-24 07:27 UTC, talentlessguy commented
@iketiunn could u pls format the readme properly, and if possible, convert the code to ESM?

2020-10-25 09:13 UTC, iketiunn commented
I refactor the example with typescript which should make the source files keep in ESM style.

2020-10-25 09:20 UTC, talentlessguy requested changes

2020-10-25 09:20 UTC, talentlessguy commented on examples/firebase-functions/tsconfig.json
> +    "target": "ES5",
pls set target to the latest that Firebase supports :3

2020-10-25 18:56 UTC, talentlessguy requested changes

2020-10-25 18:56 UTC, talentlessguy commented on examples/firebase-functions/README.md
> +## Install and login with firebase cli tool
could you please split this into two subsections of one section?

e.g.

## Firebase CLI Setup

### Install

```
// ...
```

### Login

```
// ...
```

2020-10-25 18:56 UTC, talentlessguy commented on examples/firebase-functions/README.md
> +## Install dependencies / Setup
It must be just `## Install`

2020-10-25 18:56 UTC, talentlessguy commented on examples/firebase-functions/src/index.ts
> +  // @ts-ignore
you could do `request: Request` or `request as Request`.

there's no reason to use `@ts-ignore`

2020-10-26 05:07 UTC, talentlessguy commented
LGTM, merging

2020-10-26 05:07 UTC, talentlessguy approved these changes

2020-10-26 05:07 UTC, merged

2020-10-26 05:08 UTC, talentlessguy commented
@all-contributors add @iketiunn for example